include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules for better code quality
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_const_declarations: true
    unnecessary_new: true
    unnecessary_const: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    prefer_collection_literals: true
    avoid_function_literals_in_foreach_calls: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore